### ISSUE TITLE
COPY/PASTE edits into Spanish Folder <1!-more-> translates to <!-mas-> 

### ISSUE THREAD

**Issue by NoManchesGuey** [Gorcenski/whentheycamedown#111]
@Gorcenski Do I need to translate the code prompt after photo description ex:

intro code then it appears there is description then it has a line of code which proceeds after a desc of a photo or video of the post.

Example:

Protestors on the campus of the University of North Carolina at Chapel Hill pulled down the Confederate monument commonly known as "Silent Sam." 

Los manifestantes en el campus de la Universidad de Carolina del Norte en Chapel Hill derribaron el monumento confederado comúnmente conocido como "Sam silencioso".

<! - más ->

**Comment by NoManchesGuey** [comment]
Protestors on the campus of the University of North Carolina at Chapel Hill pulled down the Confederate monument commonly known as "Silent Sam."

**Comment by Gorcenski** [comment]
No, anything in code should stay as-is.

**Comment by NoManchesGuey** [comment]
I figured as much okay, then. Is there a way to assign all these posts to me to translate? In the content/english/post folder there are many post which I need to translate but, they are in pull request mode so, it's hard to keep track of what I have done.
