### ISSUE TITLE
[CONTRIBUTION REQUEST] Edit content to add footnote citations

### ISSUE THREAD

**Issue by Gorcenski** [Gorcenski/whentheycamedown#13]
## Context

Inline links are nice, but they can make the text unreadable.

Hugo allows for footnote citations, by using the following syntax:

```
This is my text.[^1]

Here is some more text.[^2]

Now, references will go below this

#### References

[^1]: My footnote
[^2]: [This footnote is a link](url)
```

Before the references, it is nice to have an H4 (`####`) indicating that they are references. See the Robert E Lee in New Orleans source file for a working example.

### Acceptance Criteria

- [ ] Update existing content to remove inline links and replace them with footnote citations.

**Comment by bterrific2008** [comment]
Does the source file for [Robert E Lee in New Orleans](https://github.com/Gorcenski/whentheycamedown/blob/trunk/content/post/lee-new-orleans.md) use footnotes?

**Comment by Gorcenski** [comment]
As of right now, yes

**Comment by Gorcenski** [comment]
That may not have been true when I wrote the issue, because of a failed push on my end I hadn't caught

**Comment by bterrific2008** [comment]
Awesome, I see that now.

**Comment by seangtkelley** [comment]
Is anyone working on converting the existing content? If not, I can start work on my fork.
