### ISSUE TITLE
Wilmington Delaware 

### ISSUE THREAD

**Issue by jmsstnr** [Gorcenski/whentheycamedown#18]
![9BDD8985-9CFB-49E5-926F-37F591F13A97](https://user-images.githubusercontent.com/9054537/84580138-355fcf00-ada2-11ea-995f-a55239f75119.jpeg)

Columbus At Pennsylvania and N. Franklin, removed June 11th by city officials.

**Comment by eldang** [comment]
@jmsstnr Is this photo your own?  If so, how would you like it to be attributed?  If not, then can you share source/attribution info for it?

**Comment by jmsstnr** [comment]
Hi,

This is my own photo.  Attribute to Black Lives Matter/social awakening.

James Stiner

**Comment by eldang** [comment]
Thanks!  I'll wait until my first pull request is reviewed, just to make sure I have the format right.  If I do (and if no-one else beats me to it) then I'll pick this one up and add it.

**Comment by eldang** [comment]
Working on this now.
