### ISSUE TITLE
Josephus Daniels in Raleigh, NC

### ISSUE THREAD

**Issue by Thembo** [Gorcenski/whentheycamedown#25]
https://twitter.com/GrahamDavidA/status/1272882738253660161

**Comment by psivesely** [comment]
Shocked the thembo handle hadn't been snagged before.

**Comment by ligerzero459** [comment]
Seems to have been closed by #73

**Comment by Gorcenski** [comment]
Closed by https://github.com/Gorcenski/whentheycamedown/issues/25
