### ISSUE TITLE
Juan De Onate, Albuquerque, NM

### ISSUE THREAD

**Issue by Wingseven** [Gorcenski/whentheycamedown#30]
https://www.abqjournal.com/1467018/city-removes-onate-statue-after-protest-shooting-ex-two-councilors-others-questions-apds-response.html

**Comment by passcod** [comment]
Seems to be [already done](https://github.com/Gorcenski/whentheycamedown/blob/trunk/content/post/juan-de-onate.md)

**Comment by jonahbron** [comment]
https://whentheycamedown.com/post/juan-de-onate/
