### ISSUE TITLE
Thomas Jefferson, Portland, Oregon 6/16/20

### ISSUE THREAD

**Issue by Wingseven** [Gorcenski/whentheycamedown#50]

**Comment by Wingseven** [comment]
https://thehill.com/homenews/state-watch/502796-thomas-jefferson-statue-toppled-in-oregon

** Should be the 15th, not 16th **

**Comment by passcod** [comment]
This same statue was [document here already](https://github.com/Gorcenski/whentheycamedown/blob/trunk/content/english/post/jefferson-portland.md)

**Comment by shushugah** [comment]
This happened on June 14th, and is correctly labeled so in ^, will close this issue
