### ISSUE TITLE
[CONTRIBUTION REQUEST] Create a favicon

### ISSUE THREAD

**Issue by Gorcenski** [Gorcenski/whentheycamedown#7]
The website is using the theme's default favicon, which is meaningless and unintelligible.

A new favicon is needed!

**Comment by jonahbron** [comment]
I'm not exactly paid for my artistic skills, so I won't be offended if you don't take any of these contributions seriously :smile: 

Obvious, initialism:

![whentheycamedown-1](https://user-images.githubusercontent.com/607976/85208836-48195d00-b2e8-11ea-8f5f-5923d678a339.png)

More literal, meant to look like a bust falling.

![whentheycamedown-3](https://user-images.githubusercontent.com/607976/85208843-54051f00-b2e8-11ea-862c-3c26e32fe60e.png)

And a slightly more fun idea, but it's the least legible.  Meant to look like a cat paw reaching towards a bust, with the natural intent to knock it off. Would love to see someone make a better attempt at this idea :joy: 

![whentheycamedown-2](https://user-images.githubusercontent.com/607976/85208852-6b440c80-b2e8-11ea-8cb9-5c5d4b059b01.png)

**Comment by jonahbron** [comment]
Another good icon IMO would be a raised fist, but 30 minutes of trying has shown I'm incapable of making anything that looks remotely like a fist on a 16x16px grid.

**Comment by Gorcenski** [comment]
I like the second one. can i use it?

**Comment by jonahbron** [comment]
Please do.  I can make the PR if you'd like.
