### ISSUE TITLE
Second beheading of Christopher Columbus in Boston

### ISSUE THREAD

**Issue by aidapsibr** [Gorcenski/whentheycamedown#8]
Looks like this happened last night on 2020-06-09 and was reported today. Apparently this was the third time it has happened (2015 and 2006), but this time they aren't immediately fixing it.

https://boston.cbslocal.com/2020/06/10/christopher-columbus-statue-beheaded-boston-massachusetts/

**Comment by noahsbwilliams** [comment]
Opened a pull request with this included, thanks Aida!
